### ISSUE TITLE
issue chatting with bot in fm

### ISSUE THREAD

**Issue by EnterNewName** [SpectrixOfficial/Spectrum#20]
When i chat with bot it gives the output and an error

**Comment by EnterNewName** [comment]
Fucj

**Comment by SpectrixOfficial** [comment]
![image](https://user-images.githubusercontent.com/29328207/44952546-d86f7f00-ae81-11e8-9aac-ad89ec2a975f.png)
I see what you mean. I'll fix, _thank you!_

**Comment by UbnGithub** [comment]
y'know if you fixed the issue then you should close the issue

**Comment by notBanii** [comment]
^

**Comment by SpectrixOfficial** [comment]
I was away, sorry!
