### ISSUE TITLE
Bot not printing logs in bot.py

### ISSUE THREAD

**Issue by SpectrixOfficial** [SpectrixOfficial/Spectrum#4]
So I have code such as:

`    print(f"Gave my server invite to {ctx.message.author.name}. Server: {message.server.name}. Time: {datetime.datetime.now().time()}")`

after a command, and _it doesn't print it out except for the chat bot part (this is in bot.py)_

**Any thoughts?**

**Comment by notBanii** [comment]
it's `ctx.message.server.name`

**Comment by SpectrixOfficial** [comment]
_i have terminal retardation_

**Comment by SpectrixOfficial** [comment]
This is just embarrassing xD

**Comment by notBanii** [comment]
youre damn right

**Comment by SpectrixOfficial** [comment]
Oh it's still not working, even though that retarded thing was a problem, it still don't be working. I'm looking into it a bit deeper now so it's not as embarrassing

**Comment by SpectrixOfficial** [comment]
Fixed error. No further explanations needed ;)

_oh gosh why did i choose **this** to be the first issue on my repo.... seriously i've had **MUCH** worse issues than this and I choose this thing... **reeeeeeeeeeeee** me me script kiddie_

**Comment by notBanii** [comment]
you did another embarassing thing so oof

**Comment by SpectrixOfficial** [comment]
### **_not important_**
